name: Publish Charm

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish-charm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.4.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: latest/edge
