name: Publish Library

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish-lib:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Upload lib to Charmhub
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          charmcraft publish-lib charms.certificate_transfer_interface.v0.certificate_transfer
