name: Publish Charm

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish-charm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Fetch Tested Charm
        uses: actions/download-artifact@v4
        with:
          name: tested-charm
      - name: Move charm in current directory
        run: find ./ -name certificate-transfer-interface_ubuntu-22.04-amd64.charm -exec mv -t ./ {} \;
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.4.0
        with:
          built-charm-path: "certificate-transfer-interface_ubuntu-22.04-amd64.charm"
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: latest/edge
