name: Upload certificate-transfer-interface

on:
  push:
    branches:
      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-22.04
    name: Charmhub upload lib
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: canonical/charming-actions/upload-charm@2.4.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "edge"
          upload-image: "false"

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          charmcraft publish-lib charms.certificate_transfer_interface.v0.certificate_transfer
