name: Upload certificate-exchange-interface

on:
  push:
    branches:
      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-22.04
    name: Charmhub upload lib
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: canonical/charming-actions/upload-charm@2.2.5
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "edge"
          upload-image: "false"

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          charmcraft publish-lib charms.certificate_exchange_interface.v1.certificate_exchange
